language: node_js

install:
- npm install newman

script:
- node_modules/.bin/newman run tests/JSON_API_Collection.postman_collection.json -e tests/JSON_API_ENV.postman_environment.json -d tests/json_api.csv